### ISSUE TITLE
Set featured projects to reflect discover.near curation

### ISSUE THREAD

**Issue by elliotBraem** [NEARBuilders/discoverbos#20]
On the home page, featured projects is currently dummy data.

We can modify this to reflect the data stored at :

```javascript
const projects = JSON.parse(Social.get(`${context.accountId}/thing/project-registry/featured`, "final") || "null") || [];
```

**Comment by itexpert120** [comment]
Completed, no?
https://github.com/NEARBuilders/discoverbos/commit/9b92c68135da310411f9c327024b01c50c0a8c9c
