### ISSUE TITLE
project creation / submission form

### ISSUE THREAD

**Issue by jlwaugh** [NEARBuilders/discoverbos#3]
example: https://near.social/mob.near/widget/WidgetSource?src=nearhorizon.near/widget/Project.Form

multi-select ~ preconfigured categories / tags from Horizon:

* DeSci
* DeFi
* Gaming
* Metaverse
* Commercial
* Sports and Entertainment
* Infrastructure
* Social
* Social Impact
* Creative
* Education

enable user to add their own

note: creating a project should also submit that project to the main "projects" curation

**Comment by elliotBraem** [comment]
@leomanza  Make sure to pull recent PR #18 

Not any big change but to avoid any conflicts.

Also -- I think we should move away from the nearhorizon form elements -- it types super slow and it bugs out when I fill in an account Id. I'd really like it if we received our "onSubmit" function from props, too

**Comment by itexpert120** [comment]
I think it types slow because of validation

**Comment by leomanza** [comment]
Thanks, guys. I've noticed the same issue with the slow experience when using nearhorizon form. I'm trying to figure out how to improve the performance of the validation process, any suggestion?

**Comment by itexpert120** [comment]
How about we make the form outside of widget and a react component? I'm sure we can pass the validated data into a Submit button which would be a BOS Widget that can access the social api.
