### ISSUE TITLE
ConnectBOS section of the Landing page

### ISSUE THREAD

**Issue by inspiratibiz** [NEARBuilders/discoverbos#46]
Remove the Project Communities

Replace with

•Regional Communities.. The links are already on the site
![Screenshot_20231104-153329_Chrome](https://github.com/NEARBuilders/discoverbos/assets/88424565/6c788a75-c634-4c7b-a3af-359ebfae7624)

**Comment by itexpert120** [comment]
<img width="831" alt="image" src="https://github.com/NEARBuilders/discoverbos/assets/46527178/6c760724-0399-4855-9a85-f45e532bf9e9">
Completed
