### ISSUE TITLE
ExploreBOS section of the landing page

### ISSUE THREAD

**Issue by inspiratibiz** [NEARBuilders/discoverbos#47]
In the ExploreBOS section of the landing page in the related links

Remove everything currently in it and replace with

• Project Page link
•Resource Page link
•Event Calendar link
![Screenshot_20231104-153436_Chrome](https://github.com/NEARBuilders/discoverbos/assets/88424565/adb0abe9-3a6f-4951-9e2b-2cfd7016b871)

**Comment by itexpert120** [comment]
<img width="960" alt="image" src="https://github.com/NEARBuilders/discoverbos/assets/46527178/0a144882-2c18-4625-a32d-8f2cf6154a89">
Completed
