### ISSUE TITLE
Footer section of the Landing page

### ISSUE THREAD

**Issue by inspiratibiz** [NEARBuilders/discoverbos#48]
•Remove the address

Replace Twitter and Telegram links with 

Twitter: https://x.com/TheblockchainOS?t=46O8ePGVxXVbjnolKRT_-w&s=09

Telegram: https://t.me/Discover_BOS
![Screenshot_20231104-153532_Chrome](https://github.com/NEARBuilders/discoverbos/assets/88424565/1dca8455-3094-468f-8b7a-a422370bbc0e)

**Comment by itexpert120** [comment]
<img width="960" alt="image" src="https://github.com/NEARBuilders/discoverbos/assets/46527178/d2dbe81b-1389-480e-b801-a56c85fef193">
Updated links and removed address
